name: Publish Package to npmjs
on:
  pull_request:

jobs:
  push-docker-image:
    name: Push image on DockerHub
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Create image meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: synopsia/whisperapi
          tags: |
            type=semver,pattern={{raw}},value={{github.ref_name}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: synopsia/whisperapi:0.0.1
          labels: ${{ steps.meta.outputs.labels }}